config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'pages#home'

  get "tasks", to: "tasks#index"
  post  "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new", as: :new

  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit

  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end


 # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
      @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end


  def show

    @task = Task.find(params[:id])
    # choper les params
  end


  def create

    @task = Task.new(tasks_params)
    @task.save
    redirect_to tasks_path
  end

  def edit

    @task = Task.find(params[:id])
  end

  def update

    @task = Task.find(params[:id])
    @task.update(tasks_params)
    @task.save
    redirect_to tasks_path
  end


  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
       <div class="container">
         <div class="row">
           <!-- <div class="col-sm-6 col-sm-offset-3"> -->
             <%= yield %>
           <!-- </div> -->
         </div>
       </div>
     </body>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Hello world</h1>

<%= link_to "Discover all tasks", tasks_path %>

app/views/tasks/_form.html.erb
<%= form_for(task)  do |f| %>

  <div class="form-group">

    <%= f.label :title  %>
    <%= f.text_field :title, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :details  %>
    <%= f.text_field :details, class: 'form-control'  %>
  </div>


  <div class="form-group">
    <p> <%= f.check_box :completed %> Already completed? </p>
  </div>

  <%= f.submit class: 'btn btn-primary'  %>

<% end %>

app/views/tasks/edit.html.erb
<h1> EDIT</h1>

<%= render 'form', task: @task %>

<%= link_to '<i class="fas fa-undo-alt"></i> back'.html_safe, tasks_path %>

app/views/tasks/index.html.erb
<h1> hello world</h1>

<% @tasks.each do |task| %>
  <ul class="list-inline">
    <li>
      <% if task.completed == true %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
    </li>
   <li>
      <%= task.title %>
      <%= link_to  "view details", task_path(task.id)  %>
   </li>


  <%= link_to edit_path(task.id) do %>
    <p> Edit your task </p>
  <% end %>

  <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, task_path(task.id), method: :delete,  data: { confirm: "Are you sure?" } %>
  </ul>

<% end %>

<%= link_to new_path do %>
  <i class="fa fa-plus"></i> Add a new task
<% end %>
<br> <br>
<%= link_to "Home page", root_path  %>

app/views/tasks/new.html.erb
<h1>new</h1>
<h2> Here you can add a task</h2>

  <%= render 'form', task: @task %>

  <%= link_to '<i class="fas fa-undo-alt"></i> back'.html_safe, tasks_path %>

app/views/tasks/show.html.erb
<h1> The details of your task</h1>

  <p> <%= @task.title  %> </p>
  <p> <%= @task.details  %> </p>

  <%= link_to '<i class="fas fa-undo-alt"></i> back'.html_safe, tasks_path %>